az: remove indonesiacentral from azure regions
* indonesiacentral is as of now only announced. 

* fixes glci publishing error:
azure.core.exceptions.ResourceExistsError: (SubscriptionNotRegistered) Cannot specify 'indonesiacentral' in target regions because the subscription is missing required feature 'Microsoft.Resources/IndonesiaCentral'. Either register your subscription with the required feature or remove the region from the target region list.